version: '3.4'

services:
  argidb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Password1
    volumes:
        - argi-data:/var/opt/mssql  

volumes:
  argi-data:
